name: youapp_test
description: YouApp Test Project by Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  flutter_spinkit: ^5.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.1
  url_launcher: ^6.1.11
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  remove_emoji_input_formatter: ^0.0.1+1
  textfield_tags: ^2.0.2
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  welltested: ^2.1.4
  formz: ^0.6.1
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  package_info_plus: ^4.1.0
  stream_transform: ^2.1.0
  dartz: ^0.10.1
  hive: ^2.2.3
  flutter_easyloading: ^3.0.5
  azure_application_insights: ^3.1.0
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  mockito:

dependency_overrides:
  intl: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
